# Generated by Django 5.2.5 on 2025-08-18 14:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='quote',
            new_name='testimonial_text',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='location',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
